version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.8.1
    - 12.8.3
    - 13.0.11
    - 13.0.16
    - 13.0.6
    - 13.1.1
    - 13.1.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.34
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
